/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -m -a kgetadaptor -- org.kde.kget.xml
 *
 * dbusxml2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef KGETADAPTOR_H
#define KGETADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.kde.kget
 */
class KGetAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.kget")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.kget\" >\n"
"    <method name=\"isDropTargetVisible\" >\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"    </method>\n"
"    <method name=\"setDropTargetVisible\" >\n"
"      <arg direction=\"in\" type=\"b\" />\n"
"    </method>\n"
"    <method name=\"isOfflineMode\" >\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"    </method>\n"
"    <method name=\"setOfflineMode\" >\n"
"      <arg direction=\"in\" type=\"b\" />\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    KGetAdaptor(QObject *parent);
    virtual ~KGetAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    bool isDropTargetVisible();
    bool isOfflineMode();
    void setDropTargetVisible(bool in0);
    void setOfflineMode(bool in0);
Q_SIGNALS: // SIGNALS
};

#endif
